INFO 2025-07-04 11:45:45,722 autoreload 3088 5464 Watching for file changes with StatReloader
INFO 2025-07-04 14:52:48,347 autoreload 23340 24348 Watching for file changes with StatReloader
INFO 2025-07-04 14:52:54,935 autoreload 23340 24348 D:\zpj\python\test0603\ops_platform\ops_platform\settings.py changed, reloading.
INFO 2025-07-04 14:52:56,509 autoreload 16944 9776 Watching for file changes with StatReloader
INFO 2025-07-04 15:17:19,141 autoreload 14332 19700 Watching for file changes with StatReloader
INFO 2025-07-04 15:44:46,257 autoreload 34292 29720 Watching for file changes with StatReloader
WARNING 2025-07-04 15:46:51,921 log 34292 11544 Bad Request: /api/v1/users/
WARNING 2025-07-04 15:46:51,921 basehttp 34292 11544 "POST /api/v1/users/ HTTP/1.1" 400 89
INFO 2025-07-04 15:47:50,738 basehttp 34292 11544 "POST /api/v1/users/ HTTP/1.1" 201 753
INFO 2025-07-04 16:01:27,122 autoreload 34292 29720 D:\zpj\python\test0603\ops_platform\navigation\models.py changed, reloading.
INFO 2025-07-04 16:01:28,970 autoreload 27352 4056 Watching for file changes with StatReloader
INFO 2025-07-04 16:03:17,863 autoreload 27352 4056 D:\zpj\python\test0603\ops_platform\ops_platform\urls.py changed, reloading.
INFO 2025-07-04 16:03:19,246 autoreload 19340 18780 Watching for file changes with StatReloader
INFO 2025-07-04 16:04:01,785 autoreload 19340 18780 D:\zpj\python\test0603\ops_platform\navigation\admin.py changed, reloading.
INFO 2025-07-04 16:04:03,562 autoreload 11096 7704 Watching for file changes with StatReloader
INFO 2025-07-04 16:04:19,582 autoreload 11096 7704 D:\zpj\python\test0603\ops_platform\navigation\apps.py changed, reloading.
INFO 2025-07-04 16:04:21,026 autoreload 17632 13200 Watching for file changes with StatReloader
INFO 2025-07-04 16:04:42,149 autoreload 17632 13200 D:\zpj\python\test0603\ops_platform\navigation\__init__.py changed, reloading.
INFO 2025-07-04 16:04:42,969 autoreload 30708 3340 Watching for file changes with StatReloader
INFO 2025-07-04 16:39:20,216 autoreload 6468 32872 Watching for file changes with StatReloader
INFO 2025-07-04 16:44:03,521 autoreload 22632 17136 Watching for file changes with StatReloader
INFO 2025-07-04 16:46:59,715 autoreload 22632 17136 D:\zpj\python\test0603\ops_platform\ops_platform\settings.py changed, reloading.
INFO 2025-07-04 16:47:00,658 autoreload 22368 20144 Watching for file changes with StatReloader
INFO 2025-07-04 16:47:10,682 autoreload 18832 12928 Watching for file changes with StatReloader
INFO 2025-07-04 16:47:49,577 autoreload 24348 13124 Watching for file changes with StatReloader
INFO 2025-07-04 16:49:20,627 autoreload 19504 31536 Watching for file changes with StatReloader
INFO 2025-07-04 16:51:00,377 basehttp 19504 6212 "POST /api/v1/users/ HTTP/1.1" 201 753
WARNING 2025-07-04 16:58:19,922 log 19504 6212 Unauthorized: /api/v1/users/profile/
WARNING 2025-07-04 16:58:19,923 basehttp 19504 6212 "GET /api/v1/users/profile/ HTTP/1.1" 401 43
ERROR 2025-07-04 17:03:26,934 log 19504 6212 Internal Server Error: /api/v1/users/login/
Traceback (most recent call last):
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\zpj\python\test0603\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'ops_platform.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\zpj\python\test0603\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\zpj\python\test0603\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\ops_platform\users\views.py", line 84, in login
    login(request, user)
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 118, in login
    request.session.cycle_key()
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 304, in cycle_key
    self.create()
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 50, in create
    self._session_key = self._get_new_session_key()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 150, in _get_new_session_key
    if not self.exists(session_key):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 46, in exists
    return self.model.objects.filter(session_key=session_key).exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\models\query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\models\sql\query.py", line 566, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1528, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zpj\python\test0603\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\zpj\python\test0603\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'ops_platform.django_session' doesn't exist")
ERROR 2025-07-04 17:03:26,942 basehttp 19504 6212 "POST /api/v1/users/login/ HTTP/1.1" 500 204074
INFO 2025-07-04 17:11:27,574 autoreload 6556 9960 Watching for file changes with StatReloader
INFO 2025-07-04 17:12:24,894 autoreload 20496 20744 Watching for file changes with StatReloader
INFO 2025-07-04 17:13:12,250 autoreload 23604 23424 Watching for file changes with StatReloader
INFO 2025-07-04 17:14:10,594 autoreload 11348 34560 Watching for file changes with StatReloader
INFO 2025-07-04 17:16:58,834 basehttp 2184 7460 "POST /api/v1/users/login/ HTTP/1.1" 200 529
INFO 2025-07-04 17:19:29,589 basehttp 2184 7460 "GET /api/v1/users/profile HTTP/1.1" 301 0
INFO 2025-07-04 17:19:31,630 basehttp 2184 10212 "GET /api/v1/users/profile/ HTTP/1.1" 200 271
INFO 2025-07-04 17:20:03,683 basehttp 2184 10212 "GET /api/v1/navigation/categories HTTP/1.1" 301 0
INFO 2025-07-04 17:20:05,740 basehttp 2184 15256 "GET /api/v1/navigation/categories/ HTTP/1.1" 200 52
INFO 2025-07-07 20:31:21,126 autoreload 28304 12464 Watching for file changes with StatReloader
INFO 2025-07-07 20:31:56,291 autoreload 34688 22576 Watching for file changes with StatReloader
INFO 2025-07-07 20:33:19,770 autoreload 3908 18880 Watching for file changes with StatReloader
INFO 2025-07-07 20:33:36,646 autoreload 37360 17508 Watching for file changes with StatReloader
INFO 2025-07-07 20:35:23,795 autoreload 37360 17508 C:\Users\87487\Desktop\python\ArtiOps\commands\admin.py changed, reloading.
INFO 2025-07-07 20:35:24,297 autoreload 30956 19016 Watching for file changes with StatReloader
INFO 2025-07-07 20:35:51,728 autoreload 28252 34424 Watching for file changes with StatReloader
INFO 2025-07-07 20:36:02,005 basehttp 30956 32808 "GET / HTTP/1.1" 302 0
WARNING 2025-07-07 20:36:02,018 log 30956 32808 Not Found: /accounts/login/
WARNING 2025-07-07 20:36:02,018 basehttp 30956 32808 "GET /accounts/login/?next=/ HTTP/1.1" 404 2958
WARNING 2025-07-07 20:36:02,267 log 30956 32808 Not Found: /favicon.ico
WARNING 2025-07-07 20:36:02,268 basehttp 30956 32808 "GET /favicon.ico HTTP/1.1" 404 2939
INFO 2025-07-07 20:36:09,486 basehttp 30956 36028 "GET /admin/login/? HTTP/1.1" 200 4182
INFO 2025-07-07 20:36:09,721 basehttp 30956 33628 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18557
INFO 2025-07-07 20:36:09,731 basehttp 30956 27932 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2025-07-07 20:36:09,737 basehttp 30956 14936 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
INFO 2025-07-07 20:36:09,744 basehttp 30956 27932 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-07-07 20:36:09,744 basehttp 30956 36028 "GET /static/admin/css/base.css HTTP/1.1" 200 21207
INFO 2025-07-07 20:36:09,745 basehttp 30956 14936 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2025-07-07 20:36:09,745 basehttp 30956 26520 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
INFO 2025-07-07 20:36:16,357 basehttp 30956 26520 "POST /admin/login/ HTTP/1.1" 200 4314
ERROR 2025-07-07 20:42:39,804 log 30956 30908 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'aritiops.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\admin\sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\auth\views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\auth\views.py", line 109, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 118, in login
    request.session.cycle_key()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 304, in cycle_key
    self.create()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 50, in create
    self._session_key = self._get_new_session_key()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 150, in _get_new_session_key
    if not self.exists(session_key):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 46, in exists
    return self.model.objects.filter(session_key=session_key).exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\sql\query.py", line 566, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1528, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'aritiops.django_session' doesn't exist")
ERROR 2025-07-07 20:42:39,810 basehttp 30956 30908 "POST /admin/login/ HTTP/1.1" 500 287575
WARNING 2025-07-07 20:42:39,907 log 30956 30908 Not Found: /favicon.ico
WARNING 2025-07-07 20:42:39,908 basehttp 30956 30908 "GET /favicon.ico HTTP/1.1" 404 2939
INFO 2025-07-07 20:42:44,334 autoreload 38712 27528 Watching for file changes with StatReloader
ERROR 2025-07-07 20:42:52,907 log 30956 30908 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'aritiops.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\admin\sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\auth\views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\auth\views.py", line 109, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 118, in login
    request.session.cycle_key()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 304, in cycle_key
    self.create()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 50, in create
    self._session_key = self._get_new_session_key()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 150, in _get_new_session_key
    if not self.exists(session_key):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 46, in exists
    return self.model.objects.filter(session_key=session_key).exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\sql\query.py", line 566, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1528, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'aritiops.django_session' doesn't exist")
ERROR 2025-07-07 20:42:52,910 basehttp 30956 30908 "POST /admin/login/ HTTP/1.1" 500 287447
INFO 2025-07-07 20:42:58,772 basehttp 30956 30908 "GET / HTTP/1.1" 302 0
WARNING 2025-07-07 20:42:58,777 log 30956 30908 Not Found: /accounts/login/
WARNING 2025-07-07 20:42:58,777 basehttp 30956 30908 "GET /accounts/login/?next=/ HTTP/1.1" 404 2958
INFO 2025-07-07 20:47:19,003 basehttp 30956 33552 "GET / HTTP/1.1" 302 0
WARNING 2025-07-07 20:47:19,006 log 30956 33552 Not Found: /accounts/login/
WARNING 2025-07-07 20:47:19,006 basehttp 30956 33552 "GET /accounts/login/?next=/ HTTP/1.1" 404 2958
WARNING 2025-07-07 20:47:19,182 log 30956 33552 Not Found: /favicon.ico
WARNING 2025-07-07 20:47:19,182 basehttp 30956 33552 "GET /favicon.ico HTTP/1.1" 404 2939
INFO 2025-07-07 20:49:45,610 autoreload 39652 32488 Watching for file changes with StatReloader
WARNING 2025-07-07 20:49:52,849 log 39652 27544 Not Found: /accounts/login/
WARNING 2025-07-07 20:49:52,851 basehttp 39652 27544 "GET /accounts/login/?next=/ HTTP/1.1" 404 2958
INFO 2025-07-07 20:49:56,906 basehttp 39652 27544 "GET / HTTP/1.1" 302 0
WARNING 2025-07-07 20:49:56,911 log 39652 27544 Not Found: /accounts/login/
WARNING 2025-07-07 20:49:56,911 basehttp 39652 27544 "GET /accounts/login/?next=/ HTTP/1.1" 404 2958
INFO 2025-07-07 20:50:12,786 basehttp 39652 33396 "GET / HTTP/1.1" 302 0
WARNING 2025-07-07 20:50:12,793 log 39652 33396 Not Found: /accounts/login/
WARNING 2025-07-07 20:50:12,794 basehttp 39652 33396 "GET /accounts/login/?next=/ HTTP/1.1" 404 2958
INFO 2025-07-07 20:50:41,084 basehttp 39652 33396 "GET /admin/login/ HTTP/1.1" 200 4182
INFO 2025-07-07 20:50:41,243 basehttp 39652 32412 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
INFO 2025-07-07 20:50:41,246 basehttp 39652 32412 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
INFO 2025-07-07 20:50:41,244 basehttp 39652 33396 "GET /static/admin/css/base.css HTTP/1.1" 200 21207
INFO 2025-07-07 20:50:41,251 basehttp 39652 33396 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2025-07-07 20:50:41,252 basehttp 39652 33396 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2025-07-07 20:50:41,251 basehttp 39652 32412 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18557
INFO 2025-07-07 20:50:41,254 basehttp 39652 32412 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
ERROR 2025-07-07 20:50:48,793 log 39652 32412 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'aritiops.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\admin\sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\auth\views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\auth\views.py", line 109, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 118, in login
    request.session.cycle_key()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 304, in cycle_key
    self.create()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 50, in create
    self._session_key = self._get_new_session_key()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 150, in _get_new_session_key
    if not self.exists(session_key):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 46, in exists
    return self.model.objects.filter(session_key=session_key).exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\sql\query.py", line 566, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1528, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'aritiops.django_session' doesn't exist")
ERROR 2025-07-07 20:50:48,823 basehttp 39652 32412 "POST /admin/login/ HTTP/1.1" 500 285526
INFO 2025-07-07 21:29:22,862 basehttp 39652 14464 "POST /admin/login/ HTTP/1.1" 302 0
INFO 2025-07-07 21:29:24,933 basehttp 39652 14464 "GET /admin/ HTTP/1.1" 200 15528
INFO 2025-07-07 21:29:24,946 basehttp 39652 14464 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-07-07 21:29:24,946 basehttp 39652 13956 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-07-07 21:29:24,947 basehttp 39652 14464 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-07-07 21:29:24,949 basehttp 39652 13956 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-07-07 21:29:24,949 basehttp 39652 14464 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-07-07 21:29:24,949 basehttp 39652 13956 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-07-07 21:29:24,950 basehttp 39652 14464 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-07-07 21:29:24,953 basehttp 39652 14464 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-07-07 21:29:24,953 basehttp 39652 13956 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
ERROR 2025-07-07 21:29:43,430 log 39652 13956 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'hosts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\ops_platform\views.py", line 21, in index
    return render(request, 'index.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\87487\Desktop\python\ArtiOps\venv\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hosts' is not a registered namespace
ERROR 2025-07-07 21:29:43,438 basehttp 39652 13956 "GET / HTTP/1.1" 500 157487
INFO 2025-07-07 21:34:14,588 autoreload 39652 32488 C:\Users\87487\Desktop\python\ArtiOps\ops_platform\urls.py changed, reloading.
INFO 2025-07-07 21:34:15,228 autoreload 31868 37720 Watching for file changes with StatReloader
INFO 2025-07-07 21:34:29,639 autoreload 32388 18412 Watching for file changes with StatReloader
INFO 2025-07-07 21:34:55,248 autoreload 36392 33932 Watching for file changes with StatReloader
INFO 2025-07-07 21:36:30,798 autoreload 36392 33932 C:\Users\87487\Desktop\python\ArtiOps\hosts\urls.py changed, reloading.
INFO 2025-07-07 21:36:31,322 autoreload 17048 18704 Watching for file changes with StatReloader
INFO 2025-07-07 21:36:38,986 autoreload 17048 18704 C:\Users\87487\Desktop\python\ArtiOps\commands\urls.py changed, reloading.
INFO 2025-07-07 21:36:39,479 autoreload 4196 27372 Watching for file changes with StatReloader
INFO 2025-07-07 21:36:53,467 basehttp 4196 6728 "GET / HTTP/1.1" 200 34118
WARNING 2025-07-07 21:36:53,491 basehttp 4196 6728 "GET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1" 404 1879
WARNING 2025-07-07 21:36:53,492 basehttp 4196 25836 "GET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1" 404 1972
WARNING 2025-07-07 21:36:53,797 basehttp 4196 28332 "GET /static/dist/css/adminlte.min.css HTTP/1.1" 404 1834
WARNING 2025-07-07 21:36:53,811 basehttp 4196 32272 "GET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1" 404 1924
WARNING 2025-07-07 21:36:53,816 basehttp 4196 26272 "GET /static/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css HTTP/1.1" 404 1936
WARNING 2025-07-07 21:36:53,816 basehttp 4196 13572 "GET /static/plugins/select2/css/select2.min.css HTTP/1.1" 404 1864
WARNING 2025-07-07 21:36:53,817 basehttp 4196 16424 "GET /static/plugins/toastr/toastr.min.css HTTP/1.1" 404 1846
WARNING 2025-07-07 21:36:53,819 basehttp 4196 11356 "GET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1" 404 1906
WARNING 2025-07-07 21:36:54,110 basehttp 4196 39328 "GET /static/plugins/jquery/jquery.min.js HTTP/1.1" 404 1843
WARNING 2025-07-07 21:36:54,127 basehttp 4196 35912 "GET /static/dist/img/AdminLTELogo.png HTTP/1.1" 404 1834
WARNING 2025-07-07 21:36:54,134 basehttp 4196 9884 "GET /static/dist/img/user2-160x160.jpg HTTP/1.1" 404 1837
WARNING 2025-07-07 21:36:54,148 basehttp 4196 20880 "GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 404 1891
WARNING 2025-07-07 21:36:54,152 basehttp 4196 25372 "GET /static/plugins/select2/js/select2.full.min.js HTTP/1.1" 404 1873
WARNING 2025-07-07 21:36:54,152 basehttp 4196 25552 "GET /static/plugins/jquery-ui/jquery-ui.min.js HTTP/1.1" 404 1861
WARNING 2025-07-07 21:36:54,428 basehttp 4196 13152 "GET /static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js HTTP/1.1" 404 1939
WARNING 2025-07-07 21:36:54,447 basehttp 4196 12684 "GET /static/dist/js/adminlte.js HTTP/1.1" 404 1816
WARNING 2025-07-07 21:36:54,458 basehttp 4196 21332 "GET /static/plugins/toastr/toastr.min.js HTTP/1.1" 404 1843
WARNING 2025-07-07 21:36:54,466 basehttp 4196 18728 "GET /static/plugins/chart.js/Chart.min.js HTTP/1.1" 404 1846
WARNING 2025-07-07 21:37:06,132 basehttp 4196 25204 "GET /static/dist/css/adminlte.min.css HTTP/1.1" 404 1834
WARNING 2025-07-07 21:37:06,141 basehttp 4196 5380 "GET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1" 404 1906
WARNING 2025-07-07 21:37:06,141 basehttp 4196 24596 "GET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1" 404 1972
WARNING 2025-07-07 21:37:06,142 basehttp 4196 19712 "GET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1" 404 1879
WARNING 2025-07-07 21:37:06,142 basehttp 4196 16324 "GET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1" 404 1924
WARNING 2025-07-07 21:37:06,142 basehttp 4196 37404 "GET /static/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css HTTP/1.1" 404 1936
WARNING 2025-07-07 21:37:06,461 basehttp 4196 3092 "GET /static/plugins/toastr/toastr.min.css HTTP/1.1" 404 1846
WARNING 2025-07-07 21:37:06,464 basehttp 4196 28036 "GET /static/plugins/select2/css/select2.min.css HTTP/1.1" 404 1864
WARNING 2025-07-07 21:37:06,469 log 4196 37108 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-07-07 21:37:06,470 basehttp 4196 37108 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3050
INFO 2025-07-07 21:37:11,866 basehttp 4196 37108 "GET / HTTP/1.1" 200 34118
WARNING 2025-07-07 21:37:11,886 basehttp 4196 37108 "GET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1" 404 1879
WARNING 2025-07-07 21:37:12,216 basehttp 4196 1372 "GET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1" 404 1906
WARNING 2025-07-07 21:37:12,218 basehttp 4196 33152 "GET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1" 404 1972
WARNING 2025-07-07 21:37:12,221 basehttp 4196 10996 "GET /static/dist/css/adminlte.min.css HTTP/1.1" 404 1834
WARNING 2025-07-07 21:37:12,224 basehttp 4196 25656 "GET /static/plugins/select2/css/select2.min.css HTTP/1.1" 404 1864
WARNING 2025-07-07 21:37:12,226 basehttp 4196 38240 "GET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1" 404 1924
WARNING 2025-07-07 21:37:12,226 basehttp 4196 39516 "GET /static/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css HTTP/1.1" 404 1936
WARNING 2025-07-07 21:37:12,545 basehttp 4196 38920 "GET /static/plugins/toastr/toastr.min.css HTTP/1.1" 404 1846
WARNING 2025-07-07 21:37:12,555 basehttp 4196 14536 "GET /static/dist/img/user2-160x160.jpg HTTP/1.1" 404 1837
WARNING 2025-07-07 21:37:12,555 basehttp 4196 15376 "GET /static/plugins/jquery/jquery.min.js HTTP/1.1" 404 1843
WARNING 2025-07-07 21:37:12,560 basehttp 4196 21768 "GET /static/dist/img/AdminLTELogo.png HTTP/1.1" 404 1834
WARNING 2025-07-07 21:37:12,561 log 4196 10944 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-07-07 21:37:12,561 basehttp 4196 10944 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3050
WARNING 2025-07-07 21:37:12,566 basehttp 4196 10944 "GET /static/plugins/jquery-ui/jquery-ui.min.js HTTP/1.1" 404 1861
WARNING 2025-07-07 21:37:12,897 basehttp 4196 19136 "GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 404 1891
WARNING 2025-07-07 21:37:12,900 basehttp 4196 5692 "GET /static/plugins/toastr/toastr.min.js HTTP/1.1" 404 1843
WARNING 2025-07-07 21:37:12,900 basehttp 4196 5440 "GET /static/plugins/select2/js/select2.full.min.js HTTP/1.1" 404 1873
WARNING 2025-07-07 21:37:12,904 basehttp 4196 3200 "GET /static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js HTTP/1.1" 404 1939
WARNING 2025-07-07 21:37:12,904 basehttp 4196 32388 "GET /static/dist/js/adminlte.js HTTP/1.1" 404 1816
WARNING 2025-07-07 21:37:12,906 basehttp 4196 2212 "GET /static/plugins/chart.js/Chart.min.js HTTP/1.1" 404 1846
INFO 2025-07-07 21:39:02,640 autoreload 4196 27372 C:\Users\87487\Desktop\python\ArtiOps\ops_platform\urls.py changed, reloading.
INFO 2025-07-07 21:39:03,165 autoreload 19188 25732 Watching for file changes with StatReloader
INFO 2025-07-07 21:39:10,677 basehttp 19188 39372 "GET / HTTP/1.1" 200 34118
WARNING 2025-07-07 21:39:10,701 basehttp 19188 39372 "GET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1" 404 1980
WARNING 2025-07-07 21:39:10,701 basehttp 19188 32752 "GET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1" 404 2073
WARNING 2025-07-07 21:39:11,021 basehttp 19188 38672 "GET /static/dist/css/adminlte.min.css HTTP/1.1" 404 1935
WARNING 2025-07-07 21:39:11,021 basehttp 19188 39892 "GET /static/plugins/select2/css/select2.min.css HTTP/1.1" 404 1965
WARNING 2025-07-07 21:39:11,021 basehttp 19188 24340 "GET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1" 404 2007
WARNING 2025-07-07 21:39:11,021 basehttp 19188 32660 "GET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1" 404 2025
WARNING 2025-07-07 21:39:11,023 basehttp 19188 33336 "GET /static/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css HTTP/1.1" 404 2037
WARNING 2025-07-07 21:39:11,023 basehttp 19188 32456 "GET /static/plugins/toastr/toastr.min.css HTTP/1.1" 404 1947
WARNING 2025-07-07 21:39:11,348 basehttp 19188 10676 "GET /static/plugins/jquery/jquery.min.js HTTP/1.1" 404 1944
WARNING 2025-07-07 21:39:11,348 basehttp 19188 20232 "GET /static/dist/img/AdminLTELogo.png HTTP/1.1" 404 1935
WARNING 2025-07-07 21:39:11,350 basehttp 19188 33252 "GET /static/dist/img/user2-160x160.jpg HTTP/1.1" 404 1938
WARNING 2025-07-07 21:39:11,354 basehttp 19188 14260 "GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 404 1992
WARNING 2025-07-07 21:39:11,354 basehttp 19188 39660 "GET /static/plugins/jquery-ui/jquery-ui.min.js HTTP/1.1" 404 1962
WARNING 2025-07-07 21:39:11,356 basehttp 19188 36160 "GET /static/plugins/select2/js/select2.full.min.js HTTP/1.1" 404 1974
WARNING 2025-07-07 21:39:11,677 basehttp 19188 26700 "GET /static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js HTTP/1.1" 404 2040
WARNING 2025-07-07 21:39:11,678 basehttp 19188 29356 "GET /static/plugins/toastr/toastr.min.js HTTP/1.1" 404 1944
WARNING 2025-07-07 21:39:11,678 basehttp 19188 21968 "GET /static/dist/js/adminlte.js HTTP/1.1" 404 1917
WARNING 2025-07-07 21:39:11,678 basehttp 19188 19656 "GET /static/plugins/chart.js/Chart.min.js HTTP/1.1" 404 1947
WARNING 2025-07-07 21:39:11,680 log 19188 5260 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-07-07 21:39:11,680 basehttp 19188 5260 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3177
INFO 2025-07-07 21:45:57,739 autoreload 19188 25732 C:\Users\87487\Desktop\python\ArtiOps\ops_platform\settings.py changed, reloading.
INFO 2025-07-07 21:45:58,258 autoreload 18816 39736 Watching for file changes with StatReloader
INFO 2025-07-07 21:46:07,257 autoreload 18816 39736 C:\Users\87487\Desktop\python\ArtiOps\ops_platform\urls.py changed, reloading.
INFO 2025-07-07 21:46:07,759 autoreload 36028 35716 Watching for file changes with StatReloader
INFO 2025-07-07 21:47:40,719 autoreload 18384 37948 Watching for file changes with StatReloader
INFO 2025-07-07 21:47:46,148 basehttp 36028 35260 "GET / HTTP/1.1" 302 0
WARNING 2025-07-07 21:47:46,157 log 36028 35260 Not Found: /accounts/login/
WARNING 2025-07-07 21:47:46,158 basehttp 36028 35260 "GET /accounts/login/?next=/ HTTP/1.1" 404 3085
INFO 2025-07-07 21:47:51,812 basehttp 36028 35260 "GET / HTTP/1.1" 302 0
WARNING 2025-07-07 21:47:51,817 log 36028 35260 Not Found: /accounts/login/
WARNING 2025-07-07 21:47:51,818 basehttp 36028 35260 "GET /accounts/login/?next=/ HTTP/1.1" 404 3085
INFO 2025-07-07 21:48:03,695 basehttp 36028 38320 "GET / HTTP/1.1" 200 34118
WARNING 2025-07-07 21:48:03,709 log 36028 38320 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-07-07 21:48:03,712 basehttp 36028 38320 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3177
INFO 2025-07-07 21:48:03,816 basehttp 36028 17700 "GET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1" 200 59305
INFO 2025-07-07 21:48:03,821 basehttp 36028 17700 "GET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css HTTP/1.1" 200 11967
INFO 2025-07-07 21:48:03,823 basehttp 36028 17700 "GET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css HTTP/1.1" 200 12505
INFO 2025-07-07 21:48:03,824 basehttp 36028 17700 "GET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css HTTP/1.1" 200 20020
INFO 2025-07-07 21:48:03,826 basehttp 36028 17700 "GET /static/plugins/select2/css/select2.min.css HTTP/1.1" 200 14966
INFO 2025-07-07 21:48:03,828 basehttp 36028 17700 "GET /static/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css HTTP/1.1" 200 6705
INFO 2025-07-07 21:48:03,829 basehttp 36028 17700 "GET /static/plugins/toastr/toastr.min.css HTTP/1.1" 200 6454
INFO 2025-07-07 21:48:03,830 basehttp 36028 17700 "GET /static/plugins/jquery/jquery.min.js HTTP/1.1" 200 89501
INFO 2025-07-07 21:48:03,833 basehttp 36028 17700 "GET /static/dist/img/user2-160x160.jpg HTTP/1.1" 200 6905
INFO 2025-07-07 21:48:03,835 basehttp 36028 17700 "GET /static/dist/img/AdminLTELogo.png HTTP/1.1" 200 2637
INFO 2025-07-07 21:48:03,837 basehttp 36028 17700 "GET /static/plugins/jquery-ui/jquery-ui.min.js HTTP/1.1" 200 254921
INFO 2025-07-07 21:48:03,841 basehttp 36028 17700 "GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 200 83253
INFO 2025-07-07 21:48:03,842 basehttp 36028 38320 "GET /static/dist/css/adminlte.min.css HTTP/1.1" 200 1396747
INFO 2025-07-07 21:48:03,842 basehttp 36028 17700 "GET /static/plugins/select2/js/select2.full.min.js HTTP/1.1" 200 79172
INFO 2025-07-07 21:48:03,844 basehttp 36028 38320 "GET /static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js HTTP/1.1" 200 42602
INFO 2025-07-07 21:48:03,845 basehttp 36028 17700 "GET /static/dist/js/adminlte.js HTTP/1.1" 200 104260
INFO 2025-07-07 21:48:03,847 basehttp 36028 38320 "GET /static/plugins/toastr/toastr.min.js HTTP/1.1" 200 5251
INFO 2025-07-07 21:48:03,847 basehttp 36028 17700 "GET /static/plugins/chart.js/Chart.min.js HTTP/1.1" 200 173077
INFO 2025-07-07 21:48:03,902 basehttp 36028 38320 "GET /static/plugins/fontawesome-free/webfonts/fa-regular-400.woff2 HTTP/1.1" 200 13224
INFO 2025-07-07 21:48:03,903 basehttp 36028 17700 "GET /static/plugins/fontawesome-free/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 78268
INFO 2025-07-07 21:48:03,921 basehttp 36028 38320 "GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js.map HTTP/1.1" 200 311239
INFO 2025-07-07 21:48:03,931 basehttp 36028 17700 "GET /static/dist/css/adminlte.min.css.map HTTP/1.1" 200 3846965
INFO 2025-07-07 21:48:03,933 basehttp 36028 38320 "GET /static/dist/js/adminlte.js.map HTTP/1.1" 200 179858
INFO 2025-07-07 21:48:03,935 basehttp 36028 17700 "GET /static/plugins/toastr/toastr.js.map HTTP/1.1" 200 25633
